# Generated by Django 5.1.7 on 2025-03-30 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0002_alter_playlist_id'),
        ('songs', '0004_alter_genre_id_alter_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('53e5a846-28d1-4a3f-ac93-aeb405828848'), editable=False, primary_key=True, serialize=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_playlists', to='playlists.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_playlists', to='songs.song')),
            ],
        ),
    ]
