# Generated by Django 5.1.7 on 2025-03-30 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7514b85c-d8f8-49df-825c-a56d5360745d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
