# Generated by Django 5.1.7 on 2025-03-29 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5cf0d7-e942-4ef1-96c9-39a405e8a499'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d99c2c0d-9f6a-4466-91b8-a2094da91ce7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
