# Generated by Django 5.1.7 on 2025-03-30 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_genre_id_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f314ccc6-3cd4-4caa-807f-35feb5a11fd7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e4dfbd4-5114-4209-9830-0bd788997061'), editable=False, primary_key=True, serialize=False),
        ),
    ]
