# Generated by Django 5.2 on 2025-04-21 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['song_name'], name='songs_song_song_na_b0fe46_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='songs_song_genre_i_4408f8_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-create_at'], name='songs_song_create__d158ad_idx'),
        ),
    ]
